/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package it.robol.shiftscheduler.desktop;

import it.robol.shiftscheduler.backend.ShiftStorage;
import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.plaf.nimbus.NimbusLookAndFeel;

/**
 *
 * @author robol
 */
public class ShiftEditor extends javax.swing.JDialog {

    /**
     * Creates new form ShiftEditor
     */
    public ShiftEditor(java.awt.Frame parent, boolean modal) {        
        super(parent, modal);
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        morningShiftList = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        afternoonShiftList = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        sundayShiftList = new javax.swing.JList();
        addMorningShiftButton = new javax.swing.JButton();
        deleteMorningShiftButton = new javax.swing.JButton();
        addAfternoonShiftButton = new javax.swing.JButton();
        deleteAfternoonShiftButton = new javax.swing.JButton();
        addSundayShiftButton = new javax.swing.JButton();
        deleteSundayShiftButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("it/robol/shiftscheduler/desktop/Bundle"); // NOI18N
        setTitle(bundle.getString("ShiftEditor.title")); // NOI18N
        setName("Form"); // NOI18N

        jLabel1.setText(bundle.getString("ShiftEditor.jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        morningShiftList.setModel(new it.robol.shiftscheduler.desktop.MorningShiftListModel());
        morningShiftList.setName("morningShiftList"); // NOI18N
        jScrollPane1.setViewportView(morningShiftList);

        jLabel2.setText(bundle.getString("ShiftEditor.jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        afternoonShiftList.setModel(new AfternoonShiftListModel());
        afternoonShiftList.setName("afternoonShiftList"); // NOI18N
        jScrollPane2.setViewportView(afternoonShiftList);

        jLabel3.setText(bundle.getString("ShiftEditor.jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        sundayShiftList.setModel(new SundayShiftListModel());
        sundayShiftList.setName("sundayShiftList"); // NOI18N
        jScrollPane3.setViewportView(sundayShiftList);

        addMorningShiftButton.setText(bundle.getString("ShiftEditor.addMorningShiftButton.text")); // NOI18N
        addMorningShiftButton.setName("addMorningShiftButton"); // NOI18N
        addMorningShiftButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMorningShiftButtonActionPerformed(evt);
            }
        });

        deleteMorningShiftButton.setText(bundle.getString("ShiftEditor.deleteMorningShiftButton.text")); // NOI18N
        deleteMorningShiftButton.setName("deleteMorningShiftButton"); // NOI18N
        deleteMorningShiftButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMorningShiftButtonActionPerformed(evt);
            }
        });

        addAfternoonShiftButton.setText(bundle.getString("ShiftEditor.addAfternoonShiftButton.text")); // NOI18N
        addAfternoonShiftButton.setName("addAfternoonShiftButton"); // NOI18N
        addAfternoonShiftButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAfternoonShiftButtonActionPerformed(evt);
            }
        });

        deleteAfternoonShiftButton.setText(bundle.getString("ShiftEditor.deleteAfternoonShiftButton.text")); // NOI18N
        deleteAfternoonShiftButton.setName("deleteAfternoonShiftButton"); // NOI18N
        deleteAfternoonShiftButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAfternoonShiftButtonActionPerformed(evt);
            }
        });

        addSundayShiftButton.setText(bundle.getString("ShiftEditor.addSundayShiftButton.text")); // NOI18N
        addSundayShiftButton.setName("addSundayShiftButton"); // NOI18N
        addSundayShiftButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSundayShiftButtonActionPerformed(evt);
            }
        });

        deleteSundayShiftButton.setText(bundle.getString("ShiftEditor.deleteSundayShiftButton.text")); // NOI18N
        deleteSundayShiftButton.setName("deleteSundayShiftButton"); // NOI18N
        deleteSundayShiftButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteSundayShiftButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(deleteMorningShiftButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addMorningShiftButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(deleteAfternoonShiftButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addAfternoonShiftButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(deleteSundayShiftButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addSundayShiftButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1))
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addMorningShiftButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deleteMorningShiftButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addAfternoonShiftButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deleteAfternoonShiftButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addSundayShiftButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deleteSundayShiftButton)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addMorningShiftButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMorningShiftButtonActionPerformed
        ShiftCreateDialog d = new ShiftCreateDialog((JFrame) this.getParent(), true);
        d.setTarget("morning");
        d.setLocationRelativeTo(this);
        d.setVisible(true);
    }//GEN-LAST:event_addMorningShiftButtonActionPerformed

    private void addAfternoonShiftButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAfternoonShiftButtonActionPerformed
        ShiftCreateDialog d = new ShiftCreateDialog((JFrame) this.getParent(), true);
        d.setTarget("afternoon");
        d.setLocationRelativeTo(this);
        d.setVisible(true);
    }//GEN-LAST:event_addAfternoonShiftButtonActionPerformed

    private void addSundayShiftButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSundayShiftButtonActionPerformed
        ShiftCreateDialog d = new ShiftCreateDialog((JFrame) this.getParent(), true);
        d.setTarget("sunday");
        d.setLocationRelativeTo(this);
        d.setVisible(true);
    }//GEN-LAST:event_addSundayShiftButtonActionPerformed

    private void deleteMorningShiftButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMorningShiftButtonActionPerformed
        ShiftStorage ss = ShiftStorage.getInstance();
        int index = morningShiftList.getSelectedIndex();
        
        if (index != -1)
            ss.removeMorningShift(ss.getMorningShift(index));
    }//GEN-LAST:event_deleteMorningShiftButtonActionPerformed

    private void deleteAfternoonShiftButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAfternoonShiftButtonActionPerformed
        ShiftStorage ss = ShiftStorage.getInstance();
        int index = afternoonShiftList.getSelectedIndex();
        
        if (index != -1)
            ss.removeAfternoonShift(ss.getAfternoonShift(index));
    }//GEN-LAST:event_deleteAfternoonShiftButtonActionPerformed

    private void deleteSundayShiftButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteSundayShiftButtonActionPerformed
        ShiftStorage ss = ShiftStorage.getInstance();
        int index = sundayShiftList.getSelectedIndex();
        
        if (index != -1)
            ss.removeSundayShift(ss.getSundayShift(index));        
    }//GEN-LAST:event_deleteSundayShiftButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShiftEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShiftEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShiftEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShiftEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ShiftEditor dialog = new ShiftEditor(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAfternoonShiftButton;
    private javax.swing.JButton addMorningShiftButton;
    private javax.swing.JButton addSundayShiftButton;
    private javax.swing.JList afternoonShiftList;
    private javax.swing.JButton deleteAfternoonShiftButton;
    private javax.swing.JButton deleteMorningShiftButton;
    private javax.swing.JButton deleteSundayShiftButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList morningShiftList;
    private javax.swing.JList sundayShiftList;
    // End of variables declaration//GEN-END:variables
}
